version: 2
updates:
- package-ecosystem: npm
  directory: "/template"
  schedule:
    interval: weekly
    time: "00:00"
    timezone: Europe/Stockholm
  open-pull-requests-limit: 99
  target-branch: dev
